export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER = 'GET_USER';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTION_LOADING = 'TRANSACTION_LOADING';

export const GET_STOCKS = 'GET_STOCKS';
export const STOCK_LOADING = 'STOCK_LOADING';